[config]

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/rofi-colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors-hyprland.conf'
output_path = '~/.config/hypr/colors-hyprland.conf'

[templates.alacritty]
input_path = '~/.config/matugen/templates/colors-alacritty.toml'
output_path = '~/.config/alacritty/colors-alacritty.toml'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors-waybar.css'
output_path = '~/.config/waybar/colors-waybar.css'

[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc'
output_path = '~/.config/dunst/dunstrc'

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/gtk.css'
