[colors.bright]
black = '#899296' 
blue = '#89B4FA' 
cyan = '#94E2D5' 
green = '#A6E3A1' 
magenta = '#F5C2E7' 
red = '#F38BA8' 
white = '#A6ADC8' 
yellow = '#F9E2AF' 
 
[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = '#45475A' 
blue = '#89B4FA' 
cyan = '#94E2D5' 
green = '#A6E3A1' 
magenta = '#F5C2E7' 
red = '#F38BA8' 
white = '#BAC2DE' 
yellow = '#F9E2AF' 

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = '#181818' 
blue = '#86d1ea' 
cyan = '#b3cad4' 
green = '#86d1ea' 
magenta = '#c1c4eb' 
red = '#ffb4ab' 
white = '#BAC2DE' 
yellow = '#02677d' 

[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'
 
[colors.search.focused_match]
background= "CellForeground"
foreground = "CellBackground"
 
[colors.search.matches]
background = "CellForeground"
foreground = "CellBackground"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"
